### ISSUE TITLE
Time/Space Complexity 

### ISSUE THREAD

**Issue by sabandi** [hoanhan101/algo#6]
shouldn't it be be O(n!) instead of O(n) for Time/Space Complexity in https://github.com/hoanhan101/algo/blob/67a1c614cc0dca7d0b1fd1818c576fa8ac20f039/interviewcake/recursive_string_permutation_test.go#L25 ?

**Comment by hoanhan101** [comment]
Can you elaborate? Why is it O(n!) again?
