### ISSUE TITLE
quicksort code does not work

### ISSUE THREAD

**Issue by sathishvj** [hoanhan101/algo#8]

**Comment by hoanhan101** [comment]
Which error are you getting? I just run the test again and it seems to work fine:
```sh
➜  algo git:(master) go test -v lab/quicksort_test.go
=== RUN   TestQuicksort
--- PASS: TestQuicksort (0.00s)
PASS
```

**Comment by sathishvj** [comment]
That is so weird.  It works fine.  What was I running a test on yesterday then?  Sorry for the trouble.
